import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.form}>
        <h1 className={styles.title}>SOIOT SYSTEM</h1>
        <div className={styles.inputWrapper}>
          <input className={styles.input} type="text" placeholder="Username" />
          <span className={styles.errorMessage}>error</span>
        </div>
        <div className={styles.inputWrapper}>
          <input
            className={styles.input}
            type="password"
            placeholder="Password"
          />
          <span className={styles.errorMessage}>error</span>
        </div>
        <div className={styles.formAction}>
          <button type="submit" className={styles.loginButton}>
            LOGIN
          </button>
          <a className={styles.register} href="#">
            or create new account
          </a>
        </div>
      </form>
    </div>
  );
}
